=== 09liweis/humber/http5203/week3/people.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="people">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="person" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="first">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="attr" type="xs:string">
                                                        </xs:attribute>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="last" type="xs:string"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="bio" minOccurs="0">
                                <xs:complexType mixed="true">
                                    <xs:choice minOccurs="0" maxOccurs="unbounded">
                                        <xs:element name="magic" type="xs:string"></xs:element>
                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="position" type="xs:string">
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== 09liweis/humber/http5203/week4/people.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="people.xsl" ?>
<people xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="people.xsd">
  <person position="PHP Developer">
    <name>
	  <first>John</first>
	  <last>Doe</last>
	</name>
  </person>
  <person position="Wizard">
    <name>
	  <first attr="test">Hermione</first>
	  <last>Granger</last>
	</name>
	<bio>Harry Potter is a <magic>wizard</magic>.</bio>
  </person>
</people>

=== 09liweis/humber/http5203/week3/people.xml
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<people xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="people.xsd"><!-- xsi: xml schema instance -->
  <person position="PHP Developer">
    <name><!--this is a comment-->
		  <first>John</first>
		  <last>Doe</last>
		</name>
  </person>
  <person position="Wizard">
    <name>
		  <first attr="test">Hermione</first>
		  <last>Granger</last>
		</name>
		<bio>
			Harry Potter is a <magic>mixed content</magic>.
		</bio>
  </person>
</people>
