=== 09liweis/humber/http5203/a1/room.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="room">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="message" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="username" type="xs:string"></xs:element>
                            <xs:element name="submissiontime" type="xs:string"></xs:element>
                            <xs:element name="content" type="xs:string"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="roomid" type="xs:string" use="required"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== 09liweis/humber/http5203/a3/room.xml
<?xml version="1.0" encoding="utf-8"?>
<room xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="room.xsd">
    <message roomid="1">
        <username>Sam</username>
        <submissiontime>2017-01-27T12:23:02</submissiontime>
        <content>Hello, I am Sam</content>
    </message>
    <message roomid="1">
        <username>Sam</username>
        <submissiontime>2017-01-27T16:23:02</submissiontime>
        <content>Why no one is in this room</content>
    </message>
    <message roomid="1">
        <username>Sammy</username>
        <submissiontime>2017-01-27T18:23:02</submissiontime>
        <content>Hello Sam, I am Sammy</content>
    </message>
    <message roomid="2">
        <username>Sammy</username>
        <submissiontime>2017-01-27T12:43:02</submissiontime>
        <content>Hello, I am Sammy</content>
    </message>
    <message roomid="2">
        <username>Sam</username>
        <submissiontime>2017-01-27T14:23:02</submissiontime>
        <content>Hello Sammy, I am Sam</content>
    </message>
<message roomid="1"><content>This is a testing message</content><username>sam</username><submissiontime>2017-03-09 14:49:12</submissiontime></message><message roomid="1"><content>Test message</content><username>Sam</username><submissiontime>2017-03-20 22:04:09</submissiontime></message><message roomid="2"><content>This is a testing message</content><username>Sam</username><submissiontime>2017-03-20 22:04:31</submissiontime></message><message roomid=""><content/><username/><submissiontime>2017-03-26 19:44:02</submissiontime></message><message roomid=""><content/><username/><submissiontime>2017-03-26 19:50:11</submissiontime></message><message roomid="1"><content/><username/><submissiontime>2017-03-26 19:59:39</submissiontime></message><message roomid="2"><content>Yo what's up</content><username>Sam Li</username><submissiontime>2017-03-27 17:15:24</submissiontime></message><message roomid="2"><content>why is not working</content><username>Sam Li</username><submissiontime>2017-03-27 17:17:14</submissiontime></message><message roomid="2"><content>let me work</content><username>Sam Li</username><submissiontime>2017-03-27 17:17:51</submissiontime></message><message roomid="2"><content>come ont</content><username>Sam Li</username><submissiontime>2017-03-27 17:18:13</submissiontime></message><message roomid="2"><content>last try</content><username>Sam Li</username><submissiontime>2017-03-27 17:19:31</submissiontime></message><message roomid="2"><content>chat history</content><username>Sam Li</username><submissiontime>2017-03-27 18:40:52</submissiontime></message><message roomid="2"><content>Test message</content><username>Sam Li</username><submissiontime>2017-03-27 18:42:29</submissiontime></message></room>
