=== 09liweis/humber/http5203/midterm/orders.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="orders">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="order" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="customerid" type="xs:integer"></xs:element>
                            <xs:element name="status" type="xs:string"></xs:element>
                            <xs:element name="item" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"></xs:element>
                                        <xs:element name="price" type="xs:double"></xs:element>
                                        <xs:element name="qty" type="xs:integer"></xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="instock" type="instock"></xs:attribute>
                                    <xs:attribute name="itemid" type="xs:string"></xs:attribute>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="instock">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Y" />
            <xs:enumeration value="N" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== 09liweis/humber/http5203/midterm/orders.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="orders.xsl" ?>
<orders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="orders.xsd">
	<order>
		<customerid>2364</customerid>
		<status>pending</status>
		<item instock="Y" itemid="SD93">
			<name>Flying By Roller Skates</name>
			<price>25.00</price>
			<qty>25</qty>
		</item>
		<item instock="N" itemid="B12">
			<name>Bounce-o Ball</name>
			<price>.35</price>
			<qty>150</qty>
		</item>
	</order>
	<order>
		<customerid>5268</customerid>
		<status>complete</status>
		<item instock="Y" itemid="Q52">
			<name>Crash N Burn Skis</name>
			<price>20</price>
			<qty>10</qty>
		</item>
	</order>
	<order>
		<customerid>1028</customerid>
		<status>complete</status>
		<item instock="Y" itemid="BK36">
			<name>Making Crash-Test Dummies</name>
			<price>18.95</price>
			<qty>1</qty>
		</item>
		<item instock="Y" itemid="SD96">
			<name>Yak Winter Boots</name>
			<price>105.00</price>
			<qty>1</qty>
		</item>
	</order>
 </orders>
